### ISSUE TITLE
The curves of metric value and performance profile do not match with the algorithm

### ISSUE THREAD

**Issue by Ezio1018** [mantle2048/rlplot#2]
why an algorithm with good performance on the curve does not perform well on Metric value? Is there a code error?

**Comment by mantle2048** [comment]
Hi, sorry for the late reply. Could you please provide more details about the discrepancies?

Generally, the figure of metric value only present the **final** performance (specially, the mean of the last three datapoints) of the algorithm.

**Comment by Ezio1018** [comment]
I have reivised the random_score_norm_func() which did not calculate the max score of all algorithms but the max score of one algorithm.
Here is my revised version:
def random_score_norm_func(task: str, scores: List, alg_scores: dict, algos: list):
    random_score = {
        'HalfCheetah-v2': -290.0479832104089,
        'Ant-v2': -155.14243068976598,
        'Walker2d-v2': 100,
        'Humanoid-v2': 420.45141735893694,
        'Hopper-v2': 250,
        'Swimmer-v2': 20,
        'HumanoidStandup-v2': 75000,

    }
    max_temp=-10000000
    for algo in algos:
        temp=np.max(alg_scores[algo][task])
        if temp>max_temp:
            max_temp=temp
    # print(max_temp)
    # print(np.max(scores))
    scores = np.array(scores)
    nume = scores - random_score[task]
    deno = max_temp - random_score[task]
    return nume / deno
Hope you can improve the code

**Comment by Ezio1018** [comment]
By the way, could you please tell me how to get the random_score of different tasks?

**Comment by mantle2048** [comment]
Actually, you should calculate the max score of **all** algorithms instead of the max score of **one** algorithm. 

Since that in a task (e.g.`HalfCheetah-v2`), all the algorithms should be compared within the same standard, that is only the algorithm with the best performance can get the highest normalized score (maybe 1.0).


For random scores, I just utilize a random policy (e.g. `env.action_space.sample()` if you are familiar with `gym` or `gymnasium`) to sample several trajectories and calculate the mean episode return.

**Comment by Ezio1018** [comment]
But the random function in your code **doesn't** calculate the max score of all algorithms but the max score of one algorithm.

**Comment by mantle2048** [comment]
Oh, It's my bad. I only passed in one algorithm scores to the `random_score_norm_func`. 

I have fixed this in [commit 64c0227](https://github.com/mantle2048/rlplot/commit/64c022763ed466e4c2403b1caff75c95be392d55). Everything should be okay now. 

Thanks for your correction !
